name: instamarket
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http:
  built_value: ^8.1.2
  built_collection: ^5.1.1
  flutter_swiper: ^1.1.6
  redux: ^5.0.0
  freezed_annotation: ^0.15.0
  flutter_redux: ^0.8.2
  redux_epics: ^0.15.0

  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.3
  firebase_storage: ^10.0.5
  google_sign_in: ^5.1.1

  image_picker:
  location:

dependency_overrides:
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  built_value_generator: ^8.1.2
  freezed: ^0.15.0+1

flutter:
  uses-material-design: true
